### ISSUE TITLE
KeyError: 'D'

### ISSUE THREAD

**Issue by redmlr** [LearnedVector/A-Hackers-AI-Voice-Assistant#30]
I constantly getting this error: 
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pietmuller/Dokumente/code/sr.venv/speechrecognition/neuralnet/dataset.py", line 110, in __getitem__
    label = self.text_process.text_to_int_sequence(self.data['text'].iloc[idx])
  File "/Users/pietmuller/Dokumente/code/sr.venv/speechrecognition/neuralnet/utils.py", line 51, in text_to_int_sequence
    ch = self.char_map[c]
KeyError: 'D'`
I didn't change anything in the utils.py file.
I'm also wondering why it says that there is a KeyError with the character: "D". In the variable char_map_str (in utils.py) is no capital D mentioned. Also I want to train it on a common voice dataset (German to be exact)

**Comment by redmlr** [comment]
Okay I could fix this by adding some characters to the map and adding .lower() at the and of the label variable in dataset.py
But now it says that my spectrograms are to big..

**Comment by NoCodeAvaible** [comment]
Hey mate did you fix it?

**Comment by redmlr** [comment]
@NoCodeAvaible No, I couldn't, but now I am building my own automatic speech recognition system in Keras/Tensorflow.

**Comment by NoCodeAvaible** [comment]
Fixed it! Add me on Discord I'am german too so I can tell u everythink about it:) Name: SheeeshForce1#8083

**Comment by NoCodeAvaible** [comment]
If you not german I could tell you more about this because the KeyError will occur even if you lowercase.

**Comment by Jochen-sys** [comment]
@NoCodeAvaible How did you fix the error? I fixed the KeyError by changing the sentence to only lowercase letters, but I didn't fix the spectrogram which is too big. So I would be very interested how you did that.

**Comment by CracKCatZ** [comment]
@Jochen-sys it's pretty late for me I will tell you tommorow:)

**Comment by Jochen-sys** [comment]
@CracKCatZ Can you tell me now?
I originally thought I would have fixed it, but it doesn't allow the big letters. (I don't get any error, but it's not liking the big letters)
