### ISSUE TITLE
Getting an Assertion Error , i guess there is no function torchaudio.load()

### ISSUE THREAD

**Issue by raj713335** [LearnedVector/A-Hackers-AI-Voice-Assistant#32]
(venv) C:\Users\Zeus\PycharmProjects\SenSix\A-Hackers-AI-Voice-Assistant\VoiceAssistant\wakeword>engine.py  --model_file speechrecognition.zip
C:\Users\Zeus\PycharmProjects\SenSix\venv\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
C:\Users\Zeus\PycharmProjects\SenSix\venv\lib\site-packages\torchaudio\backend\utils.py:63: UserWarning: The interface of "soundfile" backend is planned to change in
 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE
= False` before setting the backend to "soundfile". Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(

*** Make sure you have sox installed on your system for the demo to work!!!
    If you don't want to use sox, change the play function in the DemoAction class
    in engine.py module to something that works with your system.

Wake Word Engine is now listening...

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Zeus\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Zeus\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Zeus\PycharmProjects\SenSix\A-Hackers-AI-Voice-Assistant\VoiceAssistant\wakeword\engine.py", line 86, in inference_loop
    action(self.predict(self.audio_q))
  File "C:\Users\Zeus\PycharmProjects\SenSix\A-Hackers-AI-Voice-Assistant\VoiceAssistant\wakeword\engine.py", line 67, in predict
    waveform, _ = torchaudio.load(fname, normalization=False)  # don't normalize on train
  File "C:\Users\Zeus\PycharmProjects\SenSix\venv\lib\site-packages\torchaudio\backend\soundfile_backend.py", line 41, in load
    assert normalization
AssertionError

**Comment by KnifeOfDunwall** [comment]
Torchauidio currently is not supported on windows, use wsl2 for that
