### ISSUE TITLE
No Default OutPut Device

### ISSUE THREAD

**Issue by raj713335** [LearnedVector/A-Hackers-AI-Voice-Assistant#33]
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM dmix
Traceback (most recent call last):
  File "engine.py", line 124, in <module>
    asr_engine = SpeechRecognitionEngine(args.model_file, args.ken_lm_file)
  File "engine.py", line 44, in __init__
    self.listener = Listener(sample_rate=8000)
  File "engine.py", line 22, in __init__
    self.stream = self.p.open(format=pyaudio.paInt16,
  File "/usr/local/lib/python3.8/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid output device (no default output device)

**Comment by KnifeOfDunwall** [comment]
More info would be good, I'm assuming you use wsl2, in that case it cannot connect to your default audio device, a workaround that might work is using pulseaudio
