### ISSUE TITLE
ModuleNotFoundError: No module named 'textprocess'

### ISSUE THREAD

**Issue by daniele777** [LearnedVector/A-Hackers-AI-Voice-Assistant#44]
Guys i import all reference to python i use Linux ( debian ) i have this error ...

2021-02-11 12:04:52.873401: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-02-11 12:04:52.873459: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/dani/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    from engine import SpeechRecognitionEngine
  File "/home/dani/Downloads/A-Hackers-AI-Voice-Assistant-master/VoiceAssistant/speechrecognition/engine.py", line 10, in <module>
    from neuralnet.dataset import get_featurizer
  File "/home/dani/Downloads/A-Hackers-AI-Voice-Assistant-master/VoiceAssistant/speechrecognition/neuralnet/dataset.py", line 6, in <module>
    from utils import TextProcess
  File "/home/dani/Downloads/A-Hackers-AI-Voice-Assistant-master/VoiceAssistant/speechrecognition/demo/utils.py", line 13, in <module>
    import textprocess
ModuleNotFoundError: No module named 'textprocess'

help!

**Comment by daniele777** [comment]
Sorry i have corrupt file all ok !
